# Controls base URL
baseURL: https://giovanis.me/
# Controls site language
languageCode: en-us
# Set Multilingual mode
defaultContentLanguage: en
languages:
  en:
    weight: 1
    contentDir: content/en
    languageName: English
  id:
    weight: 2
    contentDir: content/id
    languageName: Bahasa Indonesia
# Homepage title and page title suffix
title: giovanism
# Number of posts to show before paginating
pagination:
  pagerSize: 11

theme:
  - fractal-forest
  - after-dark

# Suggested, enable robots.txt file
enableRobotsTXT: true
# Optional, add Disqus shortname for comments
disqusShortname: ''
# Enable menu system for lazy bloggers
# sectionPagesMenu: "main"
# Provides a nicer footnote return link
footnoteReturnLinkContents: "â†©"
# Suggested, highlight fenced code blocks
pygmentsCodefences: true
# Required for custom syntax highlighting
pygmentsUseClasses: true
copyright: >-
  Copyright &copy; Giovan Isa Musthofa. Licensed under <a target="_blank"
  rel="external noopener license"
  href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.
params:
  # Suggested, controls default description meta
  description: 'simple, handy, and convenient'
  # Optional, controls author name display on posts
  author: giovanism
  # Optional, set true to hide author name on posts
  hide_author: false
  # Optional, set true to enable section menu
  show_menu: true
  # Optional, set false to disable credits
  powered_by: true
  # Suggested, controls default Open Graph images
  images:
    - https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/ASR-33_at_CHM.agr.jpg/800px-ASR-33_at_CHM.agr.jpg
  # Optional, for use to overriding default theme
  theme_variant: ''
  layout: {}
  modules:
    fractal_forest:
      # Optional, set false to disable module
      enabled: true
      # Optional, 8-bit javascript decoder with animation
      decoders:
        - bpgdec8a
menu:
  main:
    - identifier: home
      name: Home
      title: Homepage
      url: /
      weight: 1
    - identifier: about
      name: About
      title: About me
      url: /about/
      weight: 5
markup:
  goldmark:
    extensions:
      typographer: false

